Register request
WildCodeSchool/0523-RemFr-JavaAngular-P2-frontend-myserieslib pull request #33
Opened 2023-07-19 13:24 UTC by SavageD2

2023-07-19 13:30 UTC, Matthieu28 approved these changes

2023-07-19 13:35 UTC, bastienapp requested changes

2023-07-19 13:35 UTC, bastienapp commented on src/app/services/user/user.service.ts
> +    return this.http.post('http://localhost:8080/api/auth/register', user).subscribe((registerData: any) => {
ça serait bien d'utiliser la varaible d'environnement `baseApiUrl` qui existe sur dev

2023-07-20 07:20 UTC, bastienapp approved these changes
Validé :)

2023-07-20 10:29 UTC, merged